version: '3.8'

services:
    jenkins:
        build: ./jenkins/master
        image: my-jenkins/master:1.0
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        networks: 
            - jb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker
            - jenkins_home:/var/jenkins_home  # Persist Jenkins data

    jenkins-slave:
        build: ./jenkins/slave
        image: my-jenkins/slave:1.0
        container_name: jenkins-slave
        restart: always
        environment:
            - 'AGENT_SECRET=bfcd229adc127aa82a0bb4427ab8aceb173bc95e96efb51e5ceb960f8786d36a'
        ports:
            - "5005-5010:5005-5010"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose Docker daemon
            - jenkins_workspace:/home/jenkins/workspace  # Workspace data volume
        networks: 
            - jb
        depends_on:
            - jenkins

networks: 
  jb:

volumes:
  jenkins_home:    # Persistent Jenkins home volume
  jenkins_workspace:  # Persistent Jenkins slave workspace volume
